#!/bin/bash
set -euo pipefail

# ============================================================
# Clawpeteer Installer
# Installs CLI + OpenClaw Skill + MQTT config
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ---- Parse arguments ----
BROKER_URL=""
BROKER_USER=""
BROKER_PASS=""

usage() {
  echo "Usage: $0 --broker-url <url> --username <user> --password <pass>"
  echo ""
  echo "Example:"
  echo "  $0 --broker-url mqtts://your.broker.host:8883 --username my-agent --password my-secret"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --broker-url)  BROKER_URL="$2";  shift 2 ;;
    --username)    BROKER_USER="$2"; shift 2 ;;
    --password)    BROKER_PASS="$2"; shift 2 ;;
    -h|--help)     usage ;;
    *)             err "Unknown argument: $1" ;;
  esac
done

[[ -z "$BROKER_URL" ]]  && err "Missing --broker-url"
[[ -z "$BROKER_USER" ]] && err "Missing --username"
[[ -z "$BROKER_PASS" ]] && err "Missing --password"

# ---- Prerequisites ----
info "Checking prerequisites..."

if ! command -v node &>/dev/null; then
  err "Node.js is required but not found. Install it first: https://nodejs.org"
fi

NODE_VER=$(node -v | sed 's/v//' | cut -d. -f1)
if [[ "$NODE_VER" -lt 18 ]]; then
  err "Node.js >= 18 required (found: $(node -v))"
fi

if ! command -v npm &>/dev/null; then
  err "npm is required but not found."
fi

ok "Node.js $(node -v) / npm $(npm -v)"

# ---- Install CLI globally ----
info "Installing Clawpeteer CLI..."

CLI_DIR="$SCRIPT_DIR/cli"
if [[ ! -d "$CLI_DIR" ]]; then
  err "CLI directory not found at $CLI_DIR"
fi

cd "$CLI_DIR"
npm install --production 2>&1 | tail -1
npm link 2>&1 | tail -1

if command -v clawpeteer &>/dev/null; then
  ok "CLI installed: $(which clawpeteer)"
else
  warn "npm link may not have added to PATH. Trying manual symlink..."

  # Find a writable bin dir on PATH
  LOCAL_BIN=""
  for d in "$HOME/.local/bin" "$HOME/bin" "/usr/local/bin"; do
    if [[ -d "$d" ]] && echo "$PATH" | tr ':' '\n' | grep -qx "$d"; then
      LOCAL_BIN="$d"
      break
    fi
  done

  if [[ -z "$LOCAL_BIN" ]]; then
    LOCAL_BIN="$HOME/.local/bin"
    mkdir -p "$LOCAL_BIN"
    warn "Created $LOCAL_BIN — add it to PATH:"
    warn "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc && source ~/.bashrc"
  fi

  ln -sf "$CLI_DIR/bin/clawpeteer.js" "$LOCAL_BIN/clawpeteer"
  chmod +x "$CLI_DIR/bin/clawpeteer.js"
  ok "Symlinked clawpeteer -> $LOCAL_BIN/clawpeteer"
fi

# ---- Configure MQTT connection ----
info "Setting up MQTT configuration..."

CONFIG_DIR="$HOME/.clawpeteer"
mkdir -p "$CONFIG_DIR"

CA_OPT=""
if [[ -f "$SCRIPT_DIR/ca.crt" ]]; then
  cp "$SCRIPT_DIR/ca.crt" "$CONFIG_DIR/ca.crt"
  CA_OPT="\"caFile\": \"$CONFIG_DIR/ca.crt\","
  ok "CA certificate copied to $CONFIG_DIR/ca.crt"
else
  warn "No ca.crt found in package — will use system CAs"
fi

cat > "$CONFIG_DIR/config.json" <<CONF
{
  "brokerUrl": "$BROKER_URL",
  "username": "$BROKER_USER",
  "password": "$BROKER_PASS",
  ${CA_OPT}
  "_note": "Generated by Clawpeteer installer"
}
CONF

ok "Config written to $CONFIG_DIR/config.json"

# ---- Install OpenClaw Skill ----
info "Installing OpenClaw skill..."

SKILL_DIR="$HOME/.openclaw/skills/clawpeteer"
mkdir -p "$SKILL_DIR"

if [[ -f "$SCRIPT_DIR/skill/SKILL.md" ]]; then
  cp "$SCRIPT_DIR/skill/SKILL.md" "$SKILL_DIR/SKILL.md"
  ok "Skill installed to $SKILL_DIR/SKILL.md"
else
  err "SKILL.md not found in package"
fi

# ---- Verify ----
echo ""
echo -e "${GREEN}============================================================${NC}"
echo -e "${GREEN} Clawpeteer installed successfully!${NC}"
echo -e "${GREEN}============================================================${NC}"
echo ""
echo -e "  CLI:    $(command -v clawpeteer 2>/dev/null || echo "$LOCAL_BIN/clawpeteer")"
echo -e "  Config: $CONFIG_DIR/config.json"
echo -e "  Skill:  $SKILL_DIR/SKILL.md"
echo -e "  Broker: $BROKER_URL"
echo ""
echo -e "${CYAN}Quick test:${NC}"
echo "  clawpeteer list"
echo ""
